kind: pipeline
type: docker
name: wheelzone-utils-ci

trigger:
  event: [ push, pull_request ]

concurrency:
  limit: 1

steps:
  - name: clone-wz-wiki-from-vps
    image: alpine:3.20
    environment:
      WZ_VPS_SSH_KEY:
        from_secret: WZ_VPS_SSH_KEY
      WZ_WIKI_URL: "ssh://root@79.174.85.106:2222/root/git/wz-wiki.git"
      WZ_WIKI_DIR: "/drone/src/wz-wiki"
    commands:
      - apk add --no-cache git openssh ca-certificates
      - mkdir -p /root/.ssh
      - echo "$WZ_VPS_SSH_KEY" > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
      # known_hosts для нестандартного порта
      - ssh-keyscan -p 2222 -t rsa 79.174.85.106 >> /root/.ssh/known_hosts 2>/dev/null || true
      - git clone --depth 1 "$WZ_WIKI_URL" "$WZ_WIKI_DIR"
      - test -f "$WZ_WIKI_DIR/docs/security/omega_ultra_audit_protocol.md" || (echo "[WZ] Нет протокола в wz-wiki" && exit 2)

  - name: audit-protocol-check
    image: alpine:3.20
    environment:
      WIKI_DIR: "/drone/src/wz-wiki"
    commands:
      - apk add --no-cache bash git grep coreutils
      - bash ./tests/audit_protocol_check.sh

  - name: shellcheck (optional)
    image: koalaman/shellcheck-alpine:stable
    commands:
      - shellcheck ./tests/audit_protocol_check.sh || (echo "[WZ] ShellCheck fail" && exit 3)
