kind: pipeline
type: docker
name: wheelzone-utils-ci

trigger:
  event: [ push, pull_request ]

concurrency:
  limit: 1

# Глобальные переменные (могут быть переопределены секретами)
environment:
  WZ_GIT_HOST: 79.174.85.106
  WZ_GIT_PORT: "2222"
  WZ_WIKI_PATH: /root/git/wz-wiki.git
  WZ_WIKI_DIR: /drone/src/wz-wiki

steps:
  - name: clone-wz-wiki-from-vps
    image: alpine:3.20
    environment:
      WZ_VPS_SSH_KEY:
        from_secret: WZ_VPS_SSH_KEY
      # (опционально) переопределить хост/порт/путь секретами
      WZ_GIT_HOST:
        from_secret: WZ_GIT_HOST
      WZ_GIT_PORT:
        from_secret: WZ_GIT_PORT
      WZ_WIKI_PATH:
        from_secret: WZ_WIKI_PATH
    commands:
      - set -Eeuo pipefail
      - apk add --no-cache git openssh ca-certificates coreutils grep
      - : "— Подготовка SSH"
      - mkdir -p /root/.ssh
      - printf '%s\n' "$WZ_VPS_SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -p "${WZ_GIT_PORT}" -t rsa "${WZ_GIT_HOST}" >> /root/.ssh/known_hosts 2>/dev/null || true
      - : "— Клонирование wz-wiki"
      - export WZ_WIKI_URL="ssh://root@${WZ_GIT_HOST}:${WZ_GIT_PORT}${WZ_WIKI_PATH}"
      - git clone --depth 1 "$WZ_WIKI_URL" "$WZ_WIKI_DIR"
      - test -f "$WZ_WIKI_DIR/docs/security/omega_ultra_audit_protocol.md" || { echo "[WZ] Нет протокола"; exit 2; }

  - name: audit-protocol-check
    image: alpine:3.20
    environment:
      WIKI_DIR: /drone/src/wz-wiki
    commands:
      - set -Eeuo pipefail
      - apk add --no-cache bash git grep coreutils
      - bash ./tests/audit_protocol_check.sh

  - name: shellcheck
    image: koalaman/shellcheck-alpine:stable
    commands:
      - shellcheck ./tests/audit_protocol_check.sh

