kind: pipeline
type: docker
name: check-scripts

steps:
  - name: check-bash
    image: bash:5
    commands:
      - find scripts/ -name "*.sh" -exec bash -n {} \;

  - name: check-python
    image: python:3.11
    commands:
      - pip install --quiet black
      - find scripts/ -name "*.py" -exec python3 -m py_compile {} \;
      - black --check scripts/
