kind: pipeline
type: docker
name: chatend-regress

steps:
  - name: regress
    image: alpine:3.20
    environment:
      WZ_WIKI_GIT_URL:
        from_secret: WZ_WIKI_GIT_URL
      GIT_SSH_COMMAND:
        from_secret: WZ_GIT_SSH_COMMAND
    commands:
      - apk add --no-cache bash git coreutils sed grep openssh-client
      - bash scripts/ci/wz_chatend_regress_ci.sh
    when:
      event: [ push, pull_request ]
      branch: [ main, master ]

trigger:
  event: [ push, pull_request ]
