#!/data/data/com.termux/files/usr/bin/bash
# uuid: 2025-08-26T13:19:36+03:00-3717915047
# title: index_rules.sh
# component: .
# updated_at: 2025-08-26T13:19:36+03:00

# WZ Rule Indexer v1.0 — Создаёт rules_index.yaml из YAML-заголовков всех правил

set -eo pipefail
REGISTRY_FILE="${1:-$HOME/wz-wiki/registry/rules_index.yaml}"
RULES_DIR="${2:-$HOME/wz-wiki/rules}"

mkdir -p "$(dirname "$REGISTRY_FILE")"

echo "# Autogenerated index of all rules" > "$REGISTRY_FILE"
echo "---" >> "$REGISTRY_FILE"

find "$RULES_DIR" -type f -name '*.md' | while read -r file; do
  echo "- file: \"$file\"" >> "$REGISTRY_FILE"
  awk '/^---/,/^---$/ { print }' "$file" | sed '1d;$d' | awk '{ print "  " $0 }' >> "$REGISTRY_FILE"
done
