#!/data/data/com.termux/files/usr/bin/bash
# uuid: 2025-08-26T13:19:04+03:00-2121207091
# title: ce
# component: .
# updated_at: 2025-08-26T13:19:05+03:00

exec "$HOME/wheelzone-script-utils/scripts/cli/wz_chatend_safe.sh" --verbose "$@"
