version: "1.4"
patterns:
  - id: "PAT-001"
    pattern: "rm -rf"
    action: "BLOCK"
    level: "CRITICAL"
    mode: "literal"
    description: "Удаление всех файлов в директории"
    category: "file_ops"
    exceptions:
      - "rm -rf ./tmp"
      - "rm -rf build/"

  - id: "PAT-002"
    pattern: "curl.*\\|.*bash"
    action: "BLOCK"
    level: "HIGH"
    mode: "regex"
    description: "Скачивание и выполнение скрипта через pipe"
    category: "network"
    flags:
      - "case_insensitive"

  - id: "PAT-003"
    pattern: "find.*-exec.*\\\\;"
    action: "ASK"
    level: "HIGH"
    mode: "regex"
    description: "Массовое выполнение команд через find"
    category: "exec"
    action_params:
      timeout: 30
    conditions:
      - type: "user"
        value: "root"

  - id: "PAT-004"
    pattern: "dd if=.* of=/dev/sd[a-z]"
    action: "BLOCK"
    level: "CRITICAL"
    mode: "regex"
    description: "Перезапись диска через dd"
    category: "disk_ops"

  - id: "PAT-005"
    pattern: "chmod 777 -R"
    action: "ASK"
    level: "HIGH"
    mode: "literal"
    description: "Массовая выдача прав 777 на директории"
    category: "permissions"
    action_params:
      timeout: 20

  - id: "PAT-006"
    pattern: "mkfs\\."
    action: "BLOCK"
    level: "CRITICAL"
    mode: "regex"
    description: "Форматирование файловой системы"
    category: "disk_ops"

  - id: "PAT-021"
    pattern: ";"
    action: "ASK"
    level: "MEDIUM"
    mode: "literal"
    description: "Разделитель команд (возможна инъекция)"
    category: "syntax"

  - id: "PAT-022"
    pattern: "&&"
    action: "ASK"
    level: "MEDIUM"
    mode: "literal"
    description: "Цепочка команд через &&"
    category: "syntax"

  - id: "PAT-023"
    pattern: "||"
    action: "ASK"
    level: "MEDIUM"
    mode: "literal"
    description: "Цепочка команд через ||"
    category: "syntax"

  - id: "PAT-024"
    pattern: "\`.*\`"
    action: "BLOCK"
    level: "HIGH"
    mode: "regex"
    description: "Обратные кавычки для выполнения команд"
    category: "exec"

  - id: "PAT-025"
    pattern: "\\$\\(.*\\)"
    action: "BLOCK"
    level: "HIGH"
    mode: "regex"
    description: "Подстановка команд через \$()"
    category: "exec"

  - id: "PAT-026"
    pattern: ">|>>"
    action: "ASK"
    level: "MEDIUM"
    mode: "regex"
    description: "Перенаправление stdout в файл (потенциальная потеря данных)"
    category: "io"

  - id: "PAT-027"
    pattern: "2>|2>>"
    action: "ASK"
    level: "MEDIUM"
    mode: "regex"
    description: "Перенаправление stderr в файл (подавление ошибок)"
    category: "io"

  - id: "PAT-028"
    pattern: "&"
    action: "ASK"
    level: "LOW"
    mode: "literal"
    description: "Фоновое выполнение (&) — может скрывать процесс"
    category: "syntax"

  - id: "PAT-029"
    pattern: "\\|\\|"
    action: "ASK"
    level: "LOW"
    mode: "regex"
    description: "Условные конструкции через ||"
    category: "syntax"

  - id: "PAT-030"
    pattern: "\\|"
    action: "ASK"
    level: "MEDIUM"
    mode: "literal"
    description: "Pipe (передача данных между командами)"
    category: "syntax"

  - id: "PAT-031"
    pattern: "\\*"
    action: "ASK"
    level: "LOW"
    mode: "literal"
    description: "Глобальный wildcard * (может затронуть все файлы)"
    category: "file_ops"

  - id: "PAT-032"
    pattern: "\\?"
    action: "ASK"
    level: "LOW"
    mode: "literal"
    description: "Wildcard ? (один символ в имени файла)"
    category: "file_ops"

  - id: "PAT-033"
    pattern: "\\[.*\\]"
    action: "ASK"
    level: "LOW"
    mode: "regex"
    description: "Шаблон символов в имени файла [abc]"
    category: "file_ops"

  - id: "PAT-034"
    pattern: "eval "
    action: "BLOCK"
    level: "CRITICAL"
    mode: "literal"
    description: "Выполнение строки как кода через eval"
    category: "exec"

  - id: "PAT-035"
    pattern: "exec "
    action: "BLOCK"
    level: "CRITICAL"
    mode: "literal"
    description: "Замена текущего процесса через exec"
    category: "exec"


  - id: "PAT-036"
    pattern: "\\$\\(<.*\\)"
    action: "ASK"
    level: "HIGH"
    mode: "regex"
    description: "Подстановка содержимого файла через \$(<file)"
    category: "exec"

  - id: "PAT-037"
    pattern: "\\$\\{[a-zA-Z0-9_]+:-.*\\}"
    action: "ASK"
    level: "MEDIUM"
    mode: "regex"
    description: "Подстановка переменных с дефолтами \${var:-default}"
    category: "variables"

  - id: "PAT-038"
    pattern: "\\$\\{[a-zA-Z0-9_]+//.*\\}"
    action: "ASK"
    level: "MEDIUM"
    mode: "regex"
    description: "Подстановка переменных с заменами \${var//pattern/repl}"
    category: "variables"

  - id: "PAT-039"
    pattern: "\\$\\{![a-zA-Z0-9_]+\\}"
    action: "ASK"
    level: "HIGH"
    mode: "regex"
    description: "Индиректная подстановка переменных \${!var}"
    category: "variables"

  - id: "PAT-040"
    pattern: "\\$\\(\\(.*\\)\\)"
    action: "ASK"
    level: "MEDIUM"
    mode: "regex"
    description: "Арифметическая подстановка \$(( ))"
    category: "exec"

